### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by b4k0s** [rai68/oPwngrid-server#4]
![image](https://github.com/Pwnagotchi-Unofficial/oPwngrid-server/assets/152666652/72074981-529d-495d-b9dc-0d073159a8fd)

**Comment by rai68** [comment]
looks like an issue with internet sharing, I suggest checking your cables etc. Last line is a cloudflare issue, not much I can do sadly, but my tests show it only happens once every enroll of a new fingerprint.
